### ISSUE TITLE
inst wrapper files

### ISSUE THREAD

**Issue by berndbischl** [aydindemircioglu/SVMBridge#41]
I really dont see a reason to put the wrapper files not directly into the R dir o the package and export them.
this would also get rid of this here:

 addSVMPackage("LIBSVM")

I really dont see any advantage that?

**Comment by aydindemircioglu** [comment]
i think both ways are valid.
the current  design choice is to make the SVMBridge somewhat independent of the available wrappers.
wrappers are like software packages, the current philosophy is that they do not really belong to the
SVMBridge. its only convenience that they are included instead of provided at a separate webpage.

i can change that, but what are the advantages, except for saving the one line above?

**Comment by berndbischl** [comment]
R CMD check eg does not check the files in "inst".

Thats now a 2nd advantage. I am waiting for a (concrete) "pro" of yours?

**Comment by aydindemircioglu** [comment]
i still do not think that these advantages do outweigh the philosophical clearness of keeping
the SVMBridge apart from its (dirty hacked) wrappers, buuuuut--
as you wish ;)

**Comment by aydindemircioglu** [comment]
but technically, if i put all wrappers into the R folder, then they get sourced, nice.
how to find out which ones have been sourced? currently, when the user called
addSVMPackage, an entry in the (local) environment is created, and then i can
just 'getSVMMethodsAsList' and get a list of all wrappers, e.g. i can loop over.
how do i do that now? call addSVMPackage in the zzz.R script on loading the
package?

**Comment by berndbischl** [comment]
> call addSVMPackage in the zzz.R script on loading the
> package?

yes, of course

**Comment by aydindemircioglu** [comment]
thanks, its not clear to me, as an R intermediate.
but i get now different problems:
a) findAllSVMSoftware does not really work now, because if i load all the prepackaged wrappers, this command will try to find them. so if i add my own svm software (=for me still the main reason for the existence of this package), i first need to clear all wrappers in memory by 'clearSVMObjects'. so whatever i gained (not using addSVMPackage) i loose here
b) can you help me out, i dont understand how to re-add the prepackaged wrapper after clearSVMObjects. before, the wrappers were in inst/wrappers, and so they got installed along the (binary compiled) package. now, as they are part of the source, they are not in the installed packaged anymore. so do i have to copy them again by hand into inst/wrapper? or is there inst/R? so i still have to copy them by hand to re-source them?

**Comment by aydindemircioglu** [comment]
ok, i just copy the wrappers into inst/R.

**Comment by aydindemircioglu** [comment]
should work now as expected.
